import os

ASTRA_DB_API_ENDPOINT = os.getenv("ASTRA_DB_API_ENDPOINT")
ASTRA_DB_APPLICATION_TOKEN = os.getenv("ASTRA_DB_APPLICATION_TOKEN")
ASTRA_DB_NAMESPACE = os.getenv("ASTRA_DB_NAMESPACE")
IP_WHITELIST = os.environ.get("IP_WHITELIST") or ["127.0.0.1"]
GROQ_API_KEY = os.environ.get("GROQ_API_KEY")